### ISSUE TITLE
Leave domain function

### ISSUE THREAD

**Issue by bender-the-greatest** [NetDocuments/ad-join-cookbook#14]
Any plans to implement domain leave functionality?

**Comment by spuder** [comment]
No current plans because we have a wrapper script that does the `knife node delete`, `knife client delete` and removes vm from domain and hypervisor in 1 swoop. 

Pull requests are welcome.

**Comment by derekgroh** [comment]
@metalseargolid I can port something over from the windows_ad cookbook rather quickly if you're looking for just the unjoining functionality.

**Comment by bender-the-greatest** [comment]
@spuder @derekgroh I actually ended up writing in the domain unjoin functionality on my own, but I haven't had a chance to test it yet via the recipe. I'll submit a PR once I've tested and verified it works.

**Comment by derekgroh** [comment]
@metalseargolid Great, just submitted the pull request, would love to see yours for other ideas.
