### ISSUE TITLE
Syntax errors with attributes/PaxHeader/default.rb

### ISSUE THREAD

**Issue by SDBrett** [NetDocuments/ad-join-cookbook#25]
When attempting to upload the cookbook with knife I get a syntax error for each line of the attributes/PaxHeader/default.rb file.

/ad-join/attributes/PaxHeader/default.rb:1: syntax error, unexpected tIDENTIFIER, expecting keyword_end
FATAL: 18 gid=2060961091
/ad-join/attributes/PaxHeader/default.rb:2: syntax error, unexpected tIDENTIFIER, expecting keyword_end
FATAL: 18 uid=1252414916
/ad-join/attributes/PaxHeader/default.rb:3: syntax error, unexpected tIDENTIFIER, expecting keyword_end
FATAL: 20 ctime=1492190125
/ad-join/attributes/PaxHeader/default.rb:4: syntax error, unexpected tIDENTIFIER, expecting keyword_end
FATAL: 20 atime=1492190125
/ad-join/attributes/PaxHeader/default.rb:5: syntax error, unexpected tCONSTANT, expecting keyword_end
FATAL: 23 SCHILY.dev=16777220
/ad-join/attributes/PaxHeader/default.rb:6: syntax error, unexpected tCONSTANT, expecting keyword_end
FATAL: 24 SCHILY.ino=106221501
/ad-join/attributes/PaxHeader/default.rb:7: syntax error, unexpected tCONSTANT, expecting keyword_end
FATAL: 18 SCHILY.nlink=1

using version 4.12.1

**Comment by spuder** [comment]
Is this a recipe that you have added? There is no file `attributes/PaxHeader/default.rb` in the cookbook by default. 

Try using a ruby linter program to see if there is a syntax error. 

Closing since I don't think this is a problem with the cookbook itself, likely an environment issue. Reopen issue if problem is in cookbook.

**Comment by pjjohnstone** [comment]
Hi @spuder I've just downloaded v5.0.1 of this cookbook from the supermarket and I'm seeing the same issue as above.  There is an `attributes/PaxHeader/default.rb` in the cookbook folder and it doesn't seem to be valid ruby.

**Comment by pjjohnstone** [comment]
There's also a file `/PaxHeader/metadata.rb` which contains syntax errors.

**Comment by derekgroh** [comment]
Tree your cookbook directory, it does indeed sound like extra files were added.

**Comment by haragusfilip** [comment]
Hello - did you get to the bottom o this? I tried with the latest version of ad-join(5.0.2) and i have a similar issue.
/ad-join/attributes/PaxHeader/default.rb:1: syntax error, unexpected tIDENTIFIER, expecting keyword_end
FATAL: 18 gid=2060961091

**Comment by spuder** [comment]
This has to be something environmental. I just downloaded ad-join from the [supermarket](https://supermarket.chef.io/cookbooks/ad-join) and there is no PaxHeader folder. I've double checked the git repo and there is no PaxHeader folder there either. 

https://github.com/NetDocuments/ad-join-cookbook/tree/master/attributes


Are you downloading from a trusted source? 

```
ls -ial attributes/
total 0
118760445 drwxr-xr-x@  3 sowen  NV\Domain Users  102 Oct 19 12:22 .
118760440 drwxr-xr-x@ 22 sowen  NV\Domain Users  748 Nov  1 10:46 ..
118760463 -rw-r--r--@  1 sowen  NV\Domain Users    0 Oct 19 12:22 default.rb
```

**Comment by spuder** [comment]
I think this is a bug in the version of berkshelf you are using. https://github.com/berkshelf/berkshelf/issues/1132

**Comment by haragusfilip** [comment]
I downloaded it from the chef supermarket as well but i have PaxHeader folders in  the ad-join folder and in all of the subfolders. I'm using 7zip and win10 x64. If THe PaxHeader folders contains files with names similarly to the folder one level above and each file has contents like this:
18 gid=2060961091
18 uid=1252414916
20 ctime=1508437336
20 atime=1508437336
23 SCHILY.dev=16777220
24 SCHILY.ino=117850289
18 SCHILY.nlink=1

If i delete all the PaxHeader folders i am able to upload the cookbook. 
I don't have the PaxHeader folders showing up when i open with 7zip+win10 other cookbooks on the chef supermarket, so i'm thinking it might be related to the way the tar.gz is created?
![image](https://user-images.githubusercontent.com/23166769/32315457-d68dac8c-bfb4-11e7-8a02-a369bd329fa8.png)
