### ISSUE TITLE
Does not work with Chef Client 13?

### ISSUE THREAD

**Issue by coateds** [NetDocuments/ad-join-cookbook#27]
I was using this cookbook earlier this year. Currently, I am getting:

FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'ad-join' version '4.12.1' depends on chef version ["~> 12"], but the running chef version is 13.3.42

Is there something else I should be using for version 13?

-Dave

**Comment by spuder** [comment]
Correct, It does not yet support chef 13 because the windows_task resource moved from the windows cookbook to chef core. The move removed critical functionality that this cookbook depended on. Chef is activly working on making it backwards compatible. 

See 
#12 
#20 
#23

**Comment by spuder** [comment]
Chef has fixed the windows task. Hope to have this fixed for chef clients greater than 13.4.19 and released in 5.0.0

**Comment by spuder** [comment]
I'm pushing version 5.0.0 today. I have done limited testing with chef 13 and it appears to work properly. Additional testing welcome.
