### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by drum7** [NetDocuments/ad-join-cookbook#37]
NoMethodError: undefined method `double_reboot' for Chef::Resource::File

NoMethodError
    -------------
    file[c:/Windows/chef-ad-join.txt] (c:/chef/cache/cookbooks/ad-join/resources/domain_join_windows.rb line 113) had an error: NoMethodError: undefined method `double_reboot' for Chef::Resource::File

Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/ad-join/resources/domain_join_windows.rb:116:in `block (3 levels) in class_from_file'

**Comment by spuder** [comment]
Guessing you are on chef 13 or chef 14? 

Looking at line 116 it doesn't have the new_resource defined. I suspect that is causing the problem.

**Comment by spuder** [comment]
Should be fixed in 5.1.1
