### ISSUE TITLE
passwords should be single quoted

### ISSUE THREAD

**Issue by opsline-radek** [NetDocuments/ad-join-cookbook#7]
Just in case they contain special characters like `$`.

**Comment by spuder** [comment]
Looks fixed in #8

**Comment by rneu31** [comment]
Is there any additional improvements to this that will allow the ' character in a password? Or is that just something people avoid. Trying to support randomly generated passwords..

**Comment by spuder** [comment]
@rneu31 You could try something like this

password = "123'!"
password..gsub("'","\\\\'")
